// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxzBeWiUZZWiBghcHHt1hL2b7Fd0_0pc',
    appId: '1:790529659508:web:4d8029855956697194b721',
    messagingSenderId: '790529659508',
    projectId: 'chat-app-e44f9',
    authDomain: 'chat-app-e44f9.firebaseapp.com',
    storageBucket: 'chat-app-e44f9.firebasestorage.app',
    measurementId: 'G-J373FTG8JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoECp4P1z7UKZnyYREVJ4rkE0OMLVnXKU',
    appId: '1:790529659508:android:6df95e4c5b2f187194b721',
    messagingSenderId: '790529659508',
    projectId: 'chat-app-e44f9',
    storageBucket: 'chat-app-e44f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATI7E7fc6Gj1loQj3pSp-knErcXv-e6ss',
    appId: '1:790529659508:ios:50a148d6bad012e994b721',
    messagingSenderId: '790529659508',
    projectId: 'chat-app-e44f9',
    storageBucket: 'chat-app-e44f9.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );
}
